# dragmiap build index and map PanelX

samples = ["PanelX_LAB1_LIB1", "PanelX_LAB1_LIB2", "PanelX_LAB1_LIB3",
           "PanelX_LAB2_LIB1", "PanelX_LAB2_LIB2", "PanelX_LAB2_LIB3",
           "PanelX_LAB3_LIB1", "PanelX_LAB3_LIB2", "PanelX_LAB3_LIB3"]

rule all:
    input:
       expand("/home/azureuser/data/BAM/mapped/{sample}.sorted.bam", sample = samples)
       
rule dragmap_build:
    input:
        ref="/home/azureuser/data/REF/hg19.fa",
    output:
        idx=multiext(
            "hg19/",
            "hash_table.cfg",
            "hash_table.cfg.bin",
            "hash_table.cmp",
            "hash_table_stats.txt",
            "reference.bin",
            "ref_index.bin",
            "repeat_mask.bin",
            "str_table.bin",
        ),
    log:
        "logs/dragmap/hg19.build.log",
    params:
        extra="",
    threads: 2
    wrapper:
        "v1.7.0-4-g6a6d28a/bio/dragmap/build"


rule dragmap_align:
    input:
        reads=["/home/azureuser/data/FASTQ/{sample}_R1.fastq.gz", "/home/azureuser/data/FASTQ/{sample}_R2.fastq.gz"],
        idx="/home/azureuser/data/ycchen/hg19",
    output:
        "/home/azureuser/data/BAM/mapped/{sample}.sorted.bam",
    log:
        "logs/dragmap/{sample}.align.log",
    params:
        extra="",
        sorting="samtools",  # Can be 'none', 'samtools' or 'picard'.
        sort_order="coordinate",  # Can be 'queryname' or 'coordinate'.
        sort_extra="",  # Extra args for samtools/picard.
    threads: 8
    wrapper:
        "v1.7.0-4-g6a6d28a/bio/dragmap/align"
